In [30]:
import numpy as np

In [31]:
my_list=[10,20,30,40]

my_numpy_array=np.array(my_list)

my_numpy_array

array([10, 20, 30, 40])

In [32]:
my_numpy_array.max()

np.int64(40)

In [33]:
rand_array=np.random.random(5)
print(rand_array)

[0.23704506 0.73316236 0.66217003 0.18077577 0.0406158 ]


In [34]:
my_list1=[1,2]
my_list2=[3,5]

ar_1=np.array(my_list1)
ar_2=np.array(my_list2)

t=ar_1+ar_2
t

array([4, 7])

In [35]:
np_array=np.arange(0,10)
np_array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### MATRIX (ROW*COLUMN)

In [46]:
my_matrix=[[5,10],[15,20]]

np_matrix=np.array(my_matrix)
np_matrix


array([[ 5, 10],
       [15, 20]])

In [47]:
i=np_matrix[1][0]
i

np.int64(15)

##### Matrix Aritmetic

In [52]:
first_array=np.array([[10,20],[30,40]])
second_array=np.array([[5,10],[15,20]])
third_array=np.array([3,5])
forth_array=np.array([[8],[5]])

sum_array1=first_array+second_array
sum_array2=first_array+third_array
sum_array3=first_array+forth_array
sum_array3

m1=first_array*second_array
m1

array([[ 50, 200],
       [450, 800]])

In [54]:
new_array=np.random.randint(1,100,10)
new_array

array([52, 49, 15,  3, 67, 92, 55, 80, 91, 99], dtype=int32)

In [55]:
new_array[new_array>25]

array([52, 49, 67, 92, 55, 80, 91, 99], dtype=int32)

In [ ]:
new_matrix=np.array([[10,20],[30,40],[50,60]])

new_matrix.T

array([[10, 30, 50],
       [20, 40, 60]])

In [67]:
new_array2=np.random.random((4,8))
new_array2.reshape(16,2)

array([[0.12740222, 0.84853228],
       [0.91778553, 0.95125326],
       [0.42148224, 0.04525945],
       [0.38490555, 0.36925519],
       [0.74787349, 0.04942615],
       [0.95652656, 0.82581166],
       [0.98092213, 0.06101697],
       [0.31444292, 0.07439863],
       [0.16556656, 0.11706932],
       [0.76049877, 0.00757608],
       [0.68923354, 0.96695764],
       [0.85453613, 0.70317284],
       [0.7253601 , 0.43051577],
       [0.67719706, 0.94496819],
       [0.41078513, 0.51140184],
       [0.07400301, 0.83430632]])

### Z-Score

In [71]:
data=np.array([10,20,30,40,50,100,200,300])

mean=np.mean(data)
median=np.median(data)
std=np.std(data)
z_score=(data-mean)/std
z_score





array([-0.8638871 , -0.7607364 , -0.6575857 , -0.554435  , -0.4512843 ,
        0.06446919,  1.09597617,  2.12748315])